routes:
    home: 'Default:home'
    about: 'Default:about'
    contact: 'Default:contact'
    profil: 'Default:profil'
    don: 'Default:don'
    article: 'Default:article'
    offre: 'Default:offre'
    item: 'Default:item'
    thank: 'Default:thank'
    delete: 'User:delete'
    register: 'User:register'
    login: 'User:login'
    logout: 'User:logout'
    mail: 'User:mail'
    product: 'User:product'
    cause: 'User:cause'
    buy: 'User:buy'
    histo:  'User:histo'
    search: 'User:search'
    actualities: 'Default:actualities'
    partner: 'Default:partner'

defaut_route: 'home'

db_config:
    name: 'projecttransversal'
    host: 'localhost'
    user: 'root'
    pass: ''
